"""Build docs/index.html — a static mission-control dashboard for GitHub
Pages. Shows the pipeline strip (health at a glance), the scheduled queue
with exact Bluesky post previews, follower growth, engagement, and lessons.
Regenerated by every workflow before it commits."""
import html
import json
from datetime import datetime, timezone
from utils import load_config, load_json, ROOT

DOCS = ROOT / "docs"


def esc(s):
    return html.escape(str(s or ""))


def build():
    cfg = load_config()
    drafts = load_json("drafts.json", [])
    posted = load_json("posted.json", [])
    followers = load_json("follower_history.json", [])
    rejections = load_json("rejections.json", [])[-6:]
    base = cfg["media_base_url"].rstrip("/")
    handle = cfg["account"]["handle"]
    now = datetime.now(timezone.utc)

    counts = {}
    for d in drafts:
        counts[d["status"]] = counts.get(d["status"], 0) + 1
    failing = [d for d in drafts if d.get("post_failures", 0) > 0 and d["status"] == "approved"]

    def bsky_preview(d):
        c = d.get("content", {})
        imgs = (d.get("media", {}) or {}).get("bsky", [])[:4]
        img_html = "".join(
            f'<img src="{base}/{p}" alt="" loading="lazy">' for p in imgs)
        thread = "".join(
            f'<div class="reply">{esc(t)}</div>' for t in c.get("bluesky_thread", []))
        issue = f'<a class="issue" href="https://github.com/{cfg["media_base_url"].split("/")[3]}/robopost/issues/{d.get("issue","")}" target="_blank">issue #{d.get("issue","?")}</a>' if d.get("issue") else ""
        sched = ""
        if d.get("scheduled_after"):
            sched = f'<span class="chip warn">posts after {esc(d["scheduled_after"][11:16])} UTC</span>'
        return f'''<article class="post">
  <header><span class="chip {esc(d["status"])}">{esc(d["status"].replace("_"," "))}</span>
  <span class="chip">{esc(c.get("format","carousel"))}</span>{sched}{issue}</header>
  <div class="handle">{esc(handle)}</div>
  <p class="ptext">{esc(c.get("post_bluesky",""))}</p>
  <div class="imgs n{len(imgs)}">{img_html}</div>
  {thread}
</article>'''

    queue_html = "".join(bsky_preview(d) for d in reversed(drafts)
                         if d["status"] in ("in_review", "approved", "pending_review"))
    if not queue_html:
        queue_html = '<p class="empty">Queue is empty. New drafts arrive at 06:00 UTC, or add a paper by opening an issue with a link.</p>'

    recent_rows = "".join(
        f'''<tr><td class="mono">{esc(p["posted_at"][:16].replace("T"," "))}</td>
<td>{esc(p["title"][:52])}</td><td class="mono">{esc(p.get("bsky_variant","")) or "?"}</td>
<td class="mono">{esc(json.dumps(p.get("metrics",{}).get("bluesky",{})) if p.get("metrics") else "")}</td></tr>'''
        for p in reversed(posted[-15:]))

    rej_html = "".join(
        f'<li><b>{esc(r.get("title","")[:56])}</b> · {esc(r.get("reason",""))}</li>'
        for r in reversed(rejections)) or "<li>None yet.</li>"

    fdates = json.dumps([h["date"][5:] for h in followers])
    fcounts = json.dumps([h["followers"] for h in followers])
    delta = ""
    if len(followers) >= 2:
        diff = followers[-1]["followers"] - followers[-2]["followers"]
        cls = "ok" if diff >= 0 else "fail"
        delta = f'<span class="chip {cls}">{"+" if diff>=0 else ""}{diff} today</span>'

    eng_labels = json.dumps([p["posted_at"][5:10] for p in posted[-15:]])
    eng_likes = json.dumps([ (p.get("metrics",{}).get("bluesky",{}) or {}).get("likes",0) for p in posted[-15:]])
    eng_reposts = json.dumps([ (p.get("metrics",{}).get("bluesky",{}) or {}).get("reposts",0) for p in posted[-15:]])

    strip = "".join(
        f'<div class="stage"><span class="num">{counts.get(k,0)}</span><span class="lbl">{lbl}</span></div><div class="conn"></div>'
        for k, lbl in [("pending_review","rendering"),("in_review","awaiting you"),
                       ("approved","scheduled"),("posted","posted")])[:-len('<div class="conn"></div>')]

    fail_banner = ""
    if failing:
        items = ", ".join(f'#{d.get("issue","?")}' for d in failing)
        fail_banner = f'<div class="banner">Posting failed and will retry: {items}. Check the issue comments.</div>'

    page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(cfg["account"]["name"])} · mission control</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.4/chart.umd.min.js"></script>
<style>
:root{{--bg:#0E1116;--panel:#151B23;--line:#232B36;--ink:#F2F5F8;--mut:#8B95A5;
--acc:#4FD1C5;--ok:#7BD88F;--warn:#F6C177;--fail:#EB6F92}}
*{{box-sizing:border-box;margin:0}}
body{{background:var(--bg);color:var(--ink);font:15px/1.55 system-ui,-apple-system,sans-serif;padding:20px;max-width:760px;margin:0 auto}}
.mono,td.mono{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px}}
header.top h1{{font-family:ui-monospace,monospace;font-size:15px;letter-spacing:.14em;text-transform:uppercase;color:var(--acc)}}
header.top p{{color:var(--mut);font-size:13px;margin-top:2px}}
.strip{{display:flex;align-items:center;gap:8px;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:18px 0;overflow-x:auto}}
.stage{{display:flex;flex-direction:column;align-items:center;min-width:74px}}
.stage .num{{font-family:ui-monospace,monospace;font-size:26px;color:var(--acc)}}
.stage .lbl{{font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--mut)}}
.conn{{flex:1;height:1px;background:var(--line);min-width:14px}}
h2{{font-family:ui-monospace,monospace;font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:var(--mut);margin:26px 0 10px}}
.banner{{background:#2A1622;border:1px solid var(--fail);color:var(--fail);border-radius:10px;padding:10px 14px;font-size:13.5px;margin:14px 0}}
.post{{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:14px}}
.post header{{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}}
.chip{{font-family:ui-monospace,monospace;font-size:11px;padding:2px 9px;border-radius:99px;border:1px solid var(--line);color:var(--mut)}}
.chip.approved{{color:var(--warn);border-color:var(--warn)}}
.chip.in_review{{color:var(--acc);border-color:var(--acc)}}
.chip.ok{{color:var(--ok);border-color:var(--ok)}}
.chip.warn{{color:var(--warn);border-color:var(--warn)}}
.chip.fail{{color:var(--fail);border-color:var(--fail)}}
a.issue{{color:var(--acc);font-size:12px;margin-left:auto;text-decoration:none}}
.handle{{font-weight:600;font-size:14px}}
.ptext{{white-space:pre-wrap;margin:6px 0 10px}}
.imgs{{display:grid;gap:4px;border-radius:10px;overflow:hidden}}
.imgs.n1{{grid-template-columns:1fr}}.imgs.n2,.imgs.n4{{grid-template-columns:1fr 1fr}}
.imgs.n3{{grid-template-columns:1fr 1fr 1fr}}
.imgs img{{width:100%;height:auto;display:block}}
.reply{{border-left:2px solid var(--line);margin-top:10px;padding:8px 12px;color:var(--mut);font-size:14px;white-space:pre-wrap}}
.panel{{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:14px}}
table{{width:100%;border-collapse:collapse;font-size:13px}}
td{{padding:7px 8px;border-top:1px solid var(--line);vertical-align:top}}
ul{{padding-left:18px;color:var(--mut);font-size:13.5px}}
.empty{{color:var(--mut)}}
canvas{{max-height:220px}}
footer{{color:var(--mut);font-size:12px;margin:24px 0;text-align:center}}
</style></head><body>
<header class="top"><h1>{esc(cfg["account"]["name"])} · mission control</h1>
<p>{esc(handle)} · generated {now.strftime("%Y-%m-%d %H:%M")} UTC {delta}</p></header>
{fail_banner}
<div class="strip">{strip}</div>
<h2>Queue · exactly as it will post</h2>
{queue_html}
<h2>Followers</h2>
<div class="panel"><canvas id="fchart"></canvas></div>
<h2>Engagement per post (Bluesky)</h2>
<div class="panel"><canvas id="echart"></canvas></div>
<h2>Recent posts</h2>
<div class="panel"><table><tr><td class="mono">when</td><td>title</td><td class="mono">variant</td><td class="mono">bluesky</td></tr>{recent_rows}</table></div>
<h2>Recent rejections (teaching the curator)</h2>
<div class="panel"><ul>{rej_html}</ul></div>
<footer>RoboPost · data refreshes with every pipeline run</footer>
<script>
const G={{grid:{{color:"#232B36"}},ticks:{{color:"#8B95A5",font:{{size:10}}}}}};
new Chart(fchart,{{type:"line",data:{{labels:{fdates},datasets:[{{data:{fcounts},borderColor:"#4FD1C5",backgroundColor:"rgba(79,209,197,.12)",fill:true,tension:.3,pointRadius:2}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{x:G,y:G}}}}}});
new Chart(echart,{{type:"bar",data:{{labels:{eng_labels},datasets:[
 {{label:"likes",data:{eng_likes},backgroundColor:"#4FD1C5"}},
 {{label:"reposts",data:{eng_reposts},backgroundColor:"#F6C177"}}]}},
 options:{{plugins:{{legend:{{labels:{{color:"#8B95A5"}}}}}},scales:{{x:{{stacked:true,...G}},y:{{stacked:true,...G}}}}}}}});
</script></body></html>'''
    DOCS.mkdir(exist_ok=True)
    (DOCS / "index.html").write_text(page)
    print(f"Dashboard built: {len(page)//1024}KB")


if __name__ == "__main__":
    build()
